apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: katmanlimimari
type: Opaque
stringData:
  POSTGRES_PASSWORD: "YourSecurePassword123!"
  POSTGRES_USER: "postgres"
  SEQ_FIRSTRUN_ADMINPASSWORD: "SeqAdmin123!"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=katmanlimimari_db;Username=postgres;Password=YourSecurePassword123!"
